### ISSUE TITLE
Angular Cli locaton

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity-seed#41]
Hi team,

Want to ask, is there a reason for "@angular/cli": "^1.0.0-beta.30" to be in the dependencies section, and not in the devDependencies?

Not a big deal, just curious.
Thanks

**Comment by Shijir** [comment]
Hi @Jinnie, there is no reason it needs to be in dependencies. As a CLI tool, it should be in the devDependencies. Looks like it changed its position in this [commit](https://github.com/vmware/clarity-seed/commit/22e33650c2784c6211c1c54211b417cf3a496f24).  Thanks for bringing this to our attention. I will update and put it back into devDependencies in my upcoming PR.

**Comment by Jinnie** [comment]
Oh, yes. When updating from angular-cli... then I'll keep it in the devDependencies of my project too. I manually updated seed from 0.7 to 0.8, although I still keep the angular-cli.
Probably the best update strategy would be to migrate my code to a new seed project? What's your recommendation on that?

**Comment by Shijir** [comment]
@Jinnie I've just upgraded the @angular/cli version to `^1.0.0-rc.1`. So please take a look at the latest commit. I would recommend users to use the same versions of dependencies in our clarity-seed project. That's why we have `yarn` and recommend users to use it to install the dependencies. Users can manually update the version of the dependencies of our clarity-seed projects, but if they run into certain issues, we need to also manually update the dependencies like they did and try to reproduce those issues.
