### ISSUE TITLE
Styles missing when testing single component

### ISSUE THREAD

**Issue by aldialimucaj** [vmware/clarity-seed#66]
In the test example the components being tested have no styles. Is it possible to add them while testing single components?

**Comment by hippee-lee** [comment]
Hi @aldialimucaj 
The seed application specs are pretty bare bones as the goal of the seed application is to get you up and running with an angular-cli project that already has Clarity integrated into it. 

It sounds like you are looking for an example of how to test a component's style's. Is that correct?

**Comment by aldialimucaj** [comment]
Yes i would like to see an example of a test with clarity styles. The problem is without styles compomemts like grids and navigations dont render correctly.

Thanks

**Comment by hippee-lee** [comment]
I'm sorry but I'm not understanding what kind of test you are looking for. The seed project is a simple app that is intended to provide a ready made angular-cli app with Clarity already integrated.
If you want to see one approach to testing components, checkout some of the unit tests for the clarity [components](https://github.com/vmware/clarity/tree/master/src/clarity-angular) themselves. Most of those folders have an associated `component`.spec.ts file with the unit tests for that component. 

The spec examples in the `clarity-seed` are slightly modified versions of the tests generated for a new angular-cli app.They are stubs intended to be filled in after the component has been modified for an app.

It seems like this issue is about two different things:
1. How to test one of the components (home and about)
2. An issue you are having with grids and navigation

Can you make a plunker or repository that replicates your issue? I might be able to help you better if I could take a look at your code. Here is a [plunker](https://embed.plnkr.co/AuJuo5/) with clarity already integrated. You are free to fork it and post the link back here.

**Comment by aldialimucaj** [comment]
@hippee-lee Thanks for your support, it was a faulty karma configuration that caused my confusion. I made  a pull request in case you think its gonna be helpful for others.

**Comment by hippee-lee** [comment]
Thanks for the feedback and closing this issue. 
I'll take a look at the PR. 
Can you tell me about your test that was triggering this issue? Did it use something in clarity-icons that was causing the error? If possible I'd like to modify the seed-app so that it uses simple clarity examples but similar elements to your issue and make sure testing will fail if things are changed in the future.
